spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/udemy
    password: postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

